### ISSUE TITLE
Getting "Not a directory @ rb_sysopen - components/.DS_Store/Gemfile.lock"

### ISSUE THREAD

**Issue by arturopie** [dugancathal/transdeps#2]
OSX creates `.DS_Store` files for storing OS metadata. Therefore, sometimes `transdeps` will fail in Mac OS. 

I have 3 possible solutions for solving this issue:

1. Make `SpecListFactory` ignore files when collecting all specs
1. Make `SpecListFactory` ignore all *hidden* files and directories when collecting all specs
1. Add an option to pass an "ignore" list to transdeps

I'm willing to implement and submit a PR for option 1 if you are ok with that solution.

Thanks

**Comment by dugancathal** [comment]
Hey @arturopie, thanks for reaching out! Based on what I remember, and what you're saying, I think ignoring hidden files sounds like the most reasonable solution. 

That said, and based on what I'm seeing after revisiting this code, I believe the real problem lies with line 12 in the `Reconciler` - the concept of the `component_dir`'s children. If we extract _that_ to a method inside the `Reconciler` and ignore hidden file children, would that meet the need?

**Comment by arturopie** [comment]
yes, that would work. However, mind that the implementation of checking for _hidden_ files is OS dependent. Are you ok if I implement it only for Unix systems? Not sure what the portability requirements for this gem are

**Comment by arturopie** [comment]
Also, I believe it's better to just ignore any file (not just hidden files). For example, I can see people adding docs and Readme's in the `components` directory
